language: objective-c
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
script: "xcodebuild test -project Heimdall.xcodeproj -scheme Heimdall -destination \"platform=iOS Simulator,name=iPhone 6,OS=12.0\""
